export { default as TestimonialsCards } from './TestimonialsCards.astro'
export { default as AvaliacoesGoogle4249 } from './AvaliacoesGoogle4249.astro'
export { default as AvaliacoesGoogle4520 } from './AvaliacoesGoogle4520.astro'
export { default as AvaliacoesGoogle4550 } from './AvaliacoesGoogle4550.astro'
export { default as AvaliacoesGoogle1261 } from './AvaliacoesGoogle1261.astro'
